# Generated by Django 3.2.12 on 2022-05-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroom',
            options={'ordering': ['bathNum', 'location', '-size', '-cleanliness']},
        ),
        migrations.RemoveField(
            model_name='bathroom',
            name='building',
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
