# Generated by Django 4.0.3 on 2022-06-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20220503_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroom',
            options={'ordering': ['bathNum', 'location', '-size', '-cleanliness', 'gender']},
        ),
        migrations.AddField(
            model_name='bathroom',
            name='gender',
            field=models.CharField(default='Unisex', help_text='Enter Male, Female, or Unisex', max_length=10),
        ),
    ]
