# Generated by Django 4.0.3 on 2022-06-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_bathroom_options_bathroom_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='comments',
            field=models.CharField(default='No comments were made about this bathroom.', help_text='Enter a brief description of your experience in the bathroom.  Please include any negatives or positives', max_length=250),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, max_length=2),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='cleanliness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, max_length=2),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unisex', 'UNISEX')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='size',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=3, max_length=2),
        ),
    ]
