# Generated by Django 2.2.12 on 2022-05-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroom',
            options={'ordering': ['bathNum', 'location', '-size', '-cleanliness']},
        ),
        migrations.RemoveField(
            model_name='bathroom',
            name='building',
        ),
    ]
